fuzzer:
    # SAP client ID. The option is required only for testing OData services within the SAP
    # network. Useful for exmpample o ER9 env, which does not have client as part of server hostname.
    sap_client: '500'
    # A format of requested data. Valid values are 'json' and 'xml'.
    data_format: 'json'
    # A number of initial URLs which will be generated per single property  per Queriable group defined in the
    # metadata document. Currently are 4 Queriable groups, so max x4 the value from this config (can be further substracted
    # by employing restrictions to the property.
    #
    # https://github.wdf.sap.corp/ODfuzz/ODfuzz/blob/doc_architecture/doc/architecture.rst#query-groups
    # https://github.wdf.sap.corp/ODfuzz/ODfuzz/blob/doc_architecture/doc/restrictions.rst
    urls_per_property: 100

dispatcher:
    # Services which support HTTPS should have defined a security certificate. 
    certificate:
        # If true, the tool will search for a certificate in the folder where the fuzzer is
        # installed. The installation path will be added as a prefix for certificate's file
        # path. 
        cert_install_path: false
        # A file path where the HTTPS certificate is stored.
        cert_file_path: 

    # A number of asynchronous requests which will be sent to a server via dispatcher
    # at the same time.
    async_requests_num: 10
